### ISSUE TITLE
.md or .rst?

### ISSUE THREAD

**Issue by odanoburu** [labFGV/bradata#13]
I'm having trouble building our documentation as it is. it does support markdown files, but not completely (check [here](http://recommonmark.readthedocs.io/en/latest/index.html)).

I'm afraid this fragile markdown support may break in the future.

so my question is: should we go full .rst or not?

* [a .rst primer by sphinx](http://www.sphinx-doc.org/en/stable/rest.html)

**Comment by JoaoCarabetta** [comment]
it can be .rst. No problem
