### ISSUE TITLE
Call method

### ISSUE THREAD

**Issue by JoaoCarabetta** [labFGV/bradata#7]
Find a way to do this:

`bradata.infraero.statistics.get()` 

instead of:

`bradata.Infraero().statistics.get()`

**Comment by odanoburu** [comment]
this is done by having infraero be the module's name and not the class name, and having the get() method become a function in statistics.py. I'm gonna push these changes to a `call-method` branch and you guys can check how it looks like. it'll demand some refactoring, though.

**Comment by odanoburu** [comment]
@JoaoCarabetta  and @wangbarros, we should decide how our module we'll be structured as soon as possible, or we'll have to refactor a lot of code!

**Comment by odanoburu** [comment]
* bradata
    - \_\_init\_\_.py
    - utils.py
    - connection.py
    - agencias
        * \_\_init\_\_.py
        * infraero.py

this is one way of structuring the package. I'm pushing it to branch `call-method`.
to get data from infraero, we would do
```python
import bradata.agencias.infraero as infraero
infraero.get()
```
the `agencias` `__init__.py` is empty, and `infraero.py` looks like this:

```python
import bradata
from bradata.connection import Connection
import requests
from bs4 import BeautifulSoup
import time
import os


def _get_links(xml):
    """
    Get all links from a html page
    :param xml: string of a html page
    :return: links: A list of all the link in the page
    """
    soup = BeautifulSoup(xml, 'lxml')
    links = soup("a")

    return links

def get(year="2015"):

    """
    Get all statistics xls files from Infraero website for a given year
    :param year: string year, from 2017 to 2012
    :return: links: A list of all the links downloaded
    """
    database_links = set()
    conn = Connection()
    statistics_page = conn.perform_request("http://www.infraero.gov.br/index.php/br/estatisticas/estatisticas.html")
    links = _get_links(statistics_page["content"])
    for link in links:
        if (('Estatistica' in link['href']) and (year in link['href'])):
            file_name = str(link)
            file_name = file_name.split('"')[1]
            complete_link = "http://www.infraero.gov.br" + str(file_name)
            database_links.add(complete_link)
    for link in database_links:
        name = str.split(link, "/")[-1]
        print("Downloading: {}".format(link))
        resp = requests.get(link)
        with open(os.path.join(bradata.__download_dir__, "{}-{}".format(year, name)), mode='wb') as f:
            f.write(resp.content)
        time.sleep(0.05)

    return database_links
```

note that I've changed the infraero get method to download to the default download directory, that the `get_links` function was made private by adding and underscore ( `_get_links`), and that the class structure was overhauled.

if infraero becomes a submodule that offers more data, we'd make it a subfolder (instead of housing it on `agencias`). we need to have a standard way of showing the user what the library and any given submodule offers.

**Comment by odanoburu** [comment]
[so question that summarizes our options of importing](http://stackoverflow.com/questions/12229580/python-importing-a-sub-package-or-sub-modules)

[official docs](https://docs.python.org/3/tutorial/modules.html#packages)

**Comment by odanoburu** [comment]
today @JoaoCarabetta and I talked and we decided on following what is said above + importing all submodules at the bradata `__init__.py` file, plus importing all subsubmodules at a submodule's `__init__.py`.

so we have at bradata's `__init__.py`:

```python
import bradata.agencias
import bradata.cgu
import bradata.tse
import pkg_resources
```

and at cgu's `__init__.py`:

```python
import bradata.cgu.ceis
```

this allows us to call functions at subsubmodules by both

```python
import bradata.cgu.ceis as ceis
ceis.get()
```

and

```python
import bradata
bradata.cgu.ceis.get()
```

when we start having more databases in one subsubmodule, we should separate them in classes (but that's a problem for tomorrow...)
